ALTER TABLE payments
    ADD COLUMN IF NOT EXISTS store_id       VARCHAR(36) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS store_owner_id VARCHAR(36) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS commission     SMALLINT    DEFAULT 0;
