ALTER TABLE order_items
    ADD COLUMN IF NOT EXISTS variant_id TEXT,
    ADD COLUMN IF NOT EXISTS variant_sku TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS variant_label TEXT NOT NULL DEFAULT '';
